# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-tap.sh. Edits here are overwritten on
# the next release.
class Searchdeadcode < Formula
  desc "Fast CLI tool to detect dead/unused code in Android projects (Kotlin & Java)"
  homepage "https://github.com/KevinDoremy/SearchDeadCode"
  version "0.15.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/KevinDoremy/SearchDeadCode/releases/download/v0.15.0/searchdeadcode-macos-x86_64"
      sha256 "943a2358e5d3959d97fc26db4fff8fc5cd5be785bc36974eec59c75c68c16e34"
    end
    on_arm do
      url "https://github.com/KevinDoremy/SearchDeadCode/releases/download/v0.15.0/searchdeadcode-macos-aarch64"
      sha256 "ca47fbe78a486439806a737b3dedd8fd1cf9eddc3095472cc1ee008a70ab6d55"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/KevinDoremy/SearchDeadCode/releases/download/v0.15.0/searchdeadcode-linux-x86_64"
      sha256 "9275687e70004005dbc4dcd0e6dbb2aee30c6b248616d017f6bcc57fe83b57e4"
    end
    on_arm do
      url "https://github.com/KevinDoremy/SearchDeadCode/releases/download/v0.15.0/searchdeadcode-linux-aarch64"
      sha256 "99eda7cd74456cd0b8a0b7078d972843c896a6f8dcad4e8dcab900eb7f0898f7"
    end
  end

  def install
    # Homebrew downloads the single platform binary above under its asset
    # name; install it under the name users type.
    bin.install Dir["*"].first => "searchdeadcode"
  end

  test do
    assert_match "0.15.0", shell_output("#{bin}/searchdeadcode --version")
  end
end
