# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-tap.sh. Edits here are overwritten on
# the next release.
class Searchdeadcode < Formula
  desc "Fast CLI tool to detect dead/unused code in Android projects (Kotlin & Java)"
  homepage "https://github.com/KevinDoremy/SearchDeadCode"
  version "0.19.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/KevinDoremy/SearchDeadCode/releases/download/v0.19.1/searchdeadcode-macos-x86_64"
      sha256 "91f723cce00cb995d936dd3390f17ffc6b192cb731e785ece7682b709a659be3"
    end
    on_arm do
      url "https://github.com/KevinDoremy/SearchDeadCode/releases/download/v0.19.1/searchdeadcode-macos-aarch64"
      sha256 "f8766bea9a6925233b143d78b591fb37cfa7e2a9d3caae6227bf041a02c28c5d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/KevinDoremy/SearchDeadCode/releases/download/v0.19.1/searchdeadcode-linux-x86_64"
      sha256 "5c0a292a5161696e774ed5026cd438245bc9c5327a682aa9d7f21b804eec5d5d"
    end
    on_arm do
      url "https://github.com/KevinDoremy/SearchDeadCode/releases/download/v0.19.1/searchdeadcode-linux-aarch64"
      sha256 "728295a445465f89866ef92173dd50c7e64700c31ba5aed1e6f74f60c9520c3a"
    end
  end

  def install
    # Homebrew downloads the single platform binary above under its asset
    # name; install it under the name users type.
    bin.install Dir["*"].first => "searchdeadcode"
  end

  test do
    assert_match "0.19.1", shell_output("#{bin}/searchdeadcode --version")
  end
end
