# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-tap.sh. Edits here are overwritten on
# the next release.
class Searchdeadcode < Formula
  desc "Fast CLI tool to detect dead/unused code in Android projects (Kotlin & Java)"
  homepage "https://github.com/KevinDoremy/SearchDeadCode"
  version "0.13.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/KevinDoremy/SearchDeadCode/releases/download/v0.13.0/searchdeadcode-macos-x86_64"
      sha256 "5a8010b5976d43c837daf967f4fcc4523e11209c5626668f1d6851c70e6b982d"
    end
    on_arm do
      url "https://github.com/KevinDoremy/SearchDeadCode/releases/download/v0.13.0/searchdeadcode-macos-aarch64"
      sha256 "7fd5fbca822903cf44c078daa228ff73f35eea05df8d3b8b3bc09178c6247c2d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/KevinDoremy/SearchDeadCode/releases/download/v0.13.0/searchdeadcode-linux-x86_64"
      sha256 "3fb75f5d277a13c626cb8c0c34b8de9289eefd5b8c13ed7bca6f0d97fb33cb61"
    end
    on_arm do
      url "https://github.com/KevinDoremy/SearchDeadCode/releases/download/v0.13.0/searchdeadcode-linux-aarch64"
      sha256 "347c2cf68ea355b300bcd00d62871d8408273f36883066670854a566a404895c"
    end
  end

  def install
    # Homebrew downloads the single platform binary above under its asset
    # name; install it under the name users type.
    bin.install Dir["*"].first => "searchdeadcode"
  end

  test do
    assert_match "0.13.0", shell_output("#{bin}/searchdeadcode --version")
  end
end
